name: Deploy to AWS

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy Code to AWS
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SSH_HOST }} << 'EOF'
          cd /datafiles/kitchen-waste/frontend
          sudo git pull
          sudo npm install
          sudo npm run build
          sudo service nginx restart
          EOF
